name: PlayerHead
version: 1.2
main: Enes5519\PlayerHead\PlayerHead
api: [3.6.0, 3.6.1, 4.0.0]
author: Enes5519

permissions:
  playerhead:
    description: Main permission
    default: op
    children:
      playerhead.give:
        default: op
      playerhead.spawn:
        default: op
      playerhead.attack:
        default: op